baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-casper-two"
disqusShortname = ""
paginate        = 11
#SectionPagesMenu = "main"
canonifyurls    = true

# câte cuvinte să fie afișate în cardurile
# de pe prima pagină (.Summary)
summaryLength = 25

# toate variabilele aici:
# https://gohugo.io/getting-started/configuration/

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  title       = "Când Apare Revista"
  subtitle    = "Cu un picior în trecut, ochii spre viitor și... restul în prezent"
  copyright   = "© 2018"
  description = "Comunitatea revistei Level. Da, aceea de demult. Revista nu mai e, dar a a rămas forumul să stingă lumina şi lumina nu se mai stinge. Aşa că încă suntem aici: discutăm una-alta, schimbăm jocuri, scriem articole şi ne mai şi jucăm. Jocuri."

  # linkuri facebook și github
  fbName = "comunitatealevel"
  githubName = "adakaleh/candaparerevista.ro"

  metaDescription = ""
  googleAnalytics = ""
  RSSLink = ""

  # logo site si imagine fundal pentru header
  logo = "/img/car_logo.png"
  cover       = ""

  # contribuitori
  paginaContribuitori = "/contribuie"
  labelButonContribuie = "Contribuie"

  # forum
  linkForum = "https://forum.candaparerevista.ro"
  labelButonForum = "Forum"

  # autor și avatar default
  author = "car-lvl"
  authorAvatar = "/img/lvl_profile.png"
  authorDescription = "În spatele LVL e mulți."

  pageNotFoundTitle = "404 - Pagina nu gândește, deci nu există"

  # alte labels
  labelReadNext = "Alte Articole"

  #casper or caspertwo
  singleViewStyle = "casper"

  # override CSS tema
  customCSS = ["css/main-override.css", "css/art-override.css", "css/mobile-override.css", "css/fonts.css"]

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Articole"
  url = "/categories/"
  weight = 100

[[menu.main]]
  name = "Featured"
  url = "/categories/featured/"
  weight = 100

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 99

[[menu.main]]
  name = "Autori"
  url = "/authors/"
  weight = 98

[[menu.main]]
  name = "Community Blog"
  url = "/blog/"
  weight = 98

[[menu.main]]
  name = "Despre"
  url = "/despre/"
  weight = 97
