# Merge si doar "/", dar e nevoie de baseUrl pentru a forma url-uri
# absolute necesare pentru share pe facebook
baseURL = "https://candaparerevista.ro/"
languageCode = "en-us"
title = "Site-ul comunității LEVEL"
theme = "hugo-casper-two"
disqusShortname = ""
paginate        = 12
#SectionPagesMenu = "main"
canonifyurls    = true
rssLimit = 15

# câte cuvinte să fie afișate în cardurile
# de pe prima pagină (.Summary)
summaryLength = 65

# toate variabilele aici:
# https://gohugo.io/getting-started/configuration/

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  title       = "Când Apare Revista"
  subtitle    = "Jocuri vechi și noi • Site-ul comunității LEVEL"
  copyright   = "© 2018"
  description = "candaparerevista.ro este site-ul vechii comunități a revistei Level, una dintre cele mai longevive publicații despre gaming din România. După dispariția revistei în 2013, vechii utilizatori și fani s-au regrupat pe un nou forum. Pe site sunt publicate articolele și creațiile membrilor și update-uri ale proiectelor din comunitate."

  # sectiunile care sa fie afisate in lista de pe home page
  mainSections = ["post", "blog"]

  # linkuri externe: facebook, github, steam
  fbName = "comunitatealevel"
  githubName = "adakaleh/candaparerevista.ro"
  steamGroup = "candaparerevista"

  # forum
  linkForum = "https://forum.candaparerevista.ro"
  labelButonForum = "Forum"

  metaDescription = ""
  googleAnalytics = ""
  RSSLink = ""

  # logo site si imagine fundal pentru header
  logo = "/img/car_logo.png"
  cover       = "/img/site_cover.jpg"

  # dimensiuni pentru resize cover image din cards
  # (resize Height prop.: "x350", resize Width prop.: "350x")
  firstCardThumbSize = "x500"
  cardThumbSize = "x350"
  galerieThumbSize = "150x100"

  # contribuitori
  paginaContribuitori = "/contribuie"
  labelButonContribuie = "Contribuie"

  # blogul comunităţii
  labelSectiuneBlog = "Blogul Comunităţii"

  # autor și avatar default
  author = "car-lvl"
  authorAvatar = "car-lvl.png"
  authorDescription = "Dacă vezi acest text, mâine vei câștiga la loto."

  pageNotFoundTitle = "404 - Pagina nu gândește, deci nu există"

  # alte labels
  labelReadNext = "Alte Articole"

  # disclaimer review key
  disclaimerReviewKey = "Articolul a fost scris în baza unei copii de review oferite de producător."

  #casper or caspertwo
  singleViewStyle = "casper"

  # override CSS tema
  customCSS = ["css/main-override.css", "css/art-override.css", "css/mobile-override.css", "css/fonts.css"]

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Articole"
  url = "/categories/"
  weight = 100

[[menu.main]]
  name = "Featured"
  url = "/categories/featured/"
  weight = 100

[[menu.main]]
  name = "Autori"
  url = "/authors/"
  weight = 98

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 98

[[menu.pages]]
  name = "Despre"
  url = "/despre/"
  weight = 97

[[menu.pages]]
  name = "Contact"
  url = "/contact/"
  weight = 96
