baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-casper-two"
disqusShortname = ""
paginate        = 12
#SectionPagesMenu = "main"
canonifyurls    = true

# câte cuvinte să fie afișate în cardurile
# de pe prima pagină (.Summary)
summaryLength = 40

# toate variabilele aici:
# https://gohugo.io/getting-started/configuration/

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  title       = "Când Apare Revista"
  subtitle    = "Blogul Comunității Level"
  copyright   = "© 2018"
  description = "Comunitatea revistei Level. Da, aceea de demult. Revista nu mai e, dar a a rămas forumul să stingă lumina şi lumina nu se mai stinge. Aşa că încă suntem aici: discutăm una-alta, schimbăm jocuri, scriem articole şi ne mai şi jucăm. Jocuri."

  # imagine de fundal pentru site header
  cover       = ""

  metaDescription = ""
  googleAnalytics = ""
  RSSLink = ""

  # linkuri facebook și github
  fbName = "comunitatealevel"
  githubName = "adakaleh/candaparerevista.ro"

  # logo site
  logo = "/img/car_logo.png"

  # autor și avatar default
  author = "LVL"
  authorAvatar = "/img/lvl_profile.png"
  authorDescription = "În spatele LVL e mulți."

  pageNotFoundTitle = "404 - Pagina nu gândește, deci nu există"

  #casper or caspertwo
  singleViewStyle = "casper"

  # override CSS tema
  customCSS = ["css/main-override.css", "css/art-override.css", "css/mobile-override.css"]

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 100

[[menu.main]]
  name = "Categorii"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Autori"
  url = "/authors/"
  weight = 98

[[menu.main]]
  name = "Despre"
  url = "/despre/"
  weight = 97

[[menu.main]]
  name = "Forum"
  url = "https://forum.candaparerevista.ro"
  weight = 95
